name: "Build & Release"

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.2
        with:
          version: 7

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16.13.x
          cache: pnpm

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Setup git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Release
        run: ./scripts/release.sh v1
